<?php

return [

    'quotes' => [
        'happy' => [
            "Happiness looks good on you 💛",
            "Let your smile light the world.",
            "You're glowing with joy",
            "Today is a gift — unwrap it with a smile.",
            "Your joy is contagious!",
        ],
        'sad' => [
            "It's okay to feel. This too shall pass.",
            "You're doing better than you think 💙",
            "Let your tears water the seeds of strength.",
            "Healing isn’t linear. Be gentle with yourself.",
            "Sadness is just a pause, not the ending.",
        ],
        'anxious' => [
            "You are stronger than this storm.",
            "Breathe. One moment at a time",
            "Let go of what you can’t control.",
            "Even now, you are safe.",
            "Your calm is waiting within you.",
        ],
        'grateful' => [
            "Gratitude unlocks joy.",
            "Thankfulness turns what we have into enough.",
            "You are surrounded by quiet blessings.",
            "Today is a good day to be grateful",
            "Appreciation changes everything.",
        ],
        'angry' => [
            "Pause. You control your fire.",
            "Even storms settle, eventually",
            "Your anger is valid — just don’t let it own you.",
            "You are allowed to pause, not explode.",
            "Choose peace over proving a point.",
        ],
        'calm' => [
            "Peace is powerful",
            "Stillness speaks louder than noise.",
            "Let the calm carry you.",
            "Inhale quiet, exhale tension.",
            "You are anchored in peace.",
        ],
        'nostalgic' => [
            "Memories are love letters from the past.",
            "What you miss shaped who you are",
            "Some moments stay with us forever.",
            "The past holds beauty too.",
            "You are made of stories worth remembering.",
        ],
        'hopeful' => [
            "Hold on. Brighter days are ahead",
            "Even the darkest night will end.",
            "Hope is a whisper that becomes a roar.",
            "Trust the timing of your journey.",
            "Your future is filled with light.",
        ],
        'lonely' => [
            "You’re never truly alone",
            "Your presence matters more than you know.",
            "Reach inward. You are enough.",
            "You are held, even in silence.",
            "Loneliness visits, but never stays.",
        ],
        'neutral' => [
            "Stillness can be strength.",
            "Balance is beautiful",
            "Neutrality isn’t numb — it’s a breath.",
            "You’re in a moment of rest, and that’s okay.",
            "Even now, you are becoming.",
        ],
        'intense' => [
            "You are power in motion",
            "Channel your fire into creation.",
            "Intensity can be beautiful too.",
            "Strong emotions mean deep passion.",
            "You’re here. You’re alive. Own it.",
        ],
        'curious' => [
            "Curiosity is the spark of growth.",
            "Keep asking. Keep exploring",
            "Wonder is your superpower.",
            "Stay curious. Stay open.",
            "Questions open doors to magic.",
        ],
        'ambient' => [
            "Let the atmosphere hold you.",
            "Sometimes silence is the loudest support.",
            "You are floating in a safe space.",
            "Ambient isn’t empty — it’s open.",
            "Let the quiet nourish you.",
        ],
    ],

    'colors' => [
        'happy' => '#facc15',
        'sad' => '#3b82f6',
        'calm' => '#22d3ee',
        'angry' => '#ef4444',
        'nostalgic' => '#f472b6',
        'intense' => '#a855f7',
        'anxious' => '#6b7280',
        'grateful' => '#34d399',
        'curious' => '#8b5cf6',
        'lonely' => '#64748b',
        'neutral' => '#cbd5e1',
        'ambient' => '#38bdf8',
        'hopeful' => '#4ade80',
    ],
];
